# Generated by Django 5.0.1 on 2024-01-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='explanation',
        ),
        migrations.AddField(
            model_name='idea',
            name='content',
            field=models.TextField(default='default', verbose_name='설명'),
            preserve_default=False,
        ),
    ]
