# Generated by Django 5.0.1 on 2024-01-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_remove_idea_explanation_idea_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
