# Generated by Django 5.0.1 on 2024-01-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('release_data', models.IntegerField()),
                ('genre', models.CharField(choices=[('없음', 'None'), ('미스테리', 'Mistery'), ('로맨스', 'Romance'), ('드라마', 'Drama')], default='없음', max_length=16)),
                ('showtime', models.TimeField()),
                ('content', models.TextField()),
                ('director', models.CharField(max_length=16)),
                ('cast', models.CharField(max_length=50)),
            ],
        ),
    ]
