# Generated by Django 5.0.1 on 2024-01-11 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_release_data_review_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('---', 'None'), ('미스테리', 'Mistery'), ('로맨스', 'Romance'), ('드라마', 'Drama')], default='---', max_length=16),
        ),
    ]
