# Generated by Django 5.0.1 on 2024-01-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='showtime',
            field=models.IntegerField(),
        ),
    ]
