# Generated by Django 5.0.1 on 2024-01-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_showtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('불명', '불명'), ('미스테리', '미스테리'), ('로맨스', '로맨스'), ('스릴러', '스릴러'), ('판타지', '판타지'), ('액션', '액션'), ('느와르', '느와르'), ('스포츠', '스포츠'), ('코미디', '코미디'), ('전쟁', '전쟁'), ('호러', '호러'), ('음악', '음악')], default=('불명', '불명'), max_length=16),
        ),
    ]
